INSERT INTO departamentos (nombre, descripcion, habitantes) VALUES
('Amazonas', 'Departamento en el sur de Colombia, en la región amazónica.', 76000),
('Antioquia', 'Departamento en la región andina, conocido por Medellín, su capital.', 6300000),
('Arauca', 'Departamento en la región de la Orinoquía, frontera con Venezuela.', 270000),
('Atlántico', 'Departamento en la costa caribeña, con Barranquilla como su capital.', 2500000),
('Bolívar', 'Departamento caribeño, famoso por Cartagena de Indias.', 2200000),
('Boyacá', 'Departamento andino conocido por su patrimonio histórico y natural.', 1300000),
('Caldas', 'Departamento en el Eje Cafetero, con Manizales como capital.', 1000000),
('Caquetá', 'Departamento amazónico en el suroeste del país.', 400000),
('Casanare', 'Departamento de los Llanos Orientales, con una economía basada en petróleo y ganadería.', 380000),
('Cauca', 'Departamento en el suroccidente de Colombia, con gran diversidad cultural.', 1500000),
('Cesar', 'Departamento en la región caribeña, conocido por el vallenato.', 1200000),
('Chocó', 'Departamento con costa en el Pacífico y el Caribe, mayoritariamente selvático.', 550000),
('Córdoba', 'Departamento en la región caribeña, con Montería como capital.', 1700000),
('Cundinamarca', 'Departamento en la región andina que rodea a Bogotá.', 2900000),
('Guainía', 'Departamento en la región amazónica, poco poblado y en gran parte selvático.', 46000),
('Guaviare', 'Departamento amazónico con gran biodiversidad.', 83000),
('Huila', 'Departamento en la región andina, conocido por el río Magdalena.', 1200000),
('La Guajira', 'Departamento caribeño en el extremo norte, hogar de la cultura Wayúu.', 900000),
('Magdalena', 'Departamento costero en el Caribe, conocido por Santa Marta.', 1300000),
('Meta', 'Departamento de los Llanos Orientales, con Villavicencio como capital.', 1100000),
('Nariño', 'Departamento en el suroccidente, fronterizo con Ecuador.', 1900000),
('Norte de Santander', 'Departamento fronterizo con Venezuela, con Cúcuta como capital.', 1400000),
('Putumayo', 'Departamento en el suroeste amazónico, conocido por sus riquezas naturales.', 330000),
('Quindío', 'Departamento en el Eje Cafetero, con Armenia como capital.', 550000),
('Risaralda', 'Departamento en el Eje Cafetero, conocido por su producción de café.', 1000000),
('San Andrés y Providencia', 'Departamento insular en el Caribe.', 70000),
('Santander', 'Departamento en la región andina, con Bucaramanga como capital.', 2200000),
('Sucre', 'Departamento en la costa caribeña, con Sincelejo como capital.', 900000),
('Tolima', 'Departamento en la región andina, conocido por Ibagué.', 1500000),
('Valle del Cauca', 'Departamento en el suroccidente, con Cali como capital.', 4700000),
('Vaupés', 'Departamento en la región amazónica, poco poblado y mayormente selvático.', 40000),
('Vichada', 'Departamento en los Llanos Orientales, de baja densidad poblacional.', 55000);
WITH Duplicados AS (
    SELECT id,
           ROW_NUMBER() OVER (PARTITION BY nombre ORDER BY id) AS fila
    FROM departamentos
)
DELETE FROM departamentos
WHERE id IN (SELECT id FROM Duplicados WHERE fila > 1);

-- Inserción de municipios para el departamento de Amazonas (ajusta el departamento_id según el ID real en la base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Leticia', 1, 'Capital del departamento de Amazonas, fronteriza con Brasil y Perú.', 48000),
('Puerto Nariño', 1, 'Conocido como el "pesebre de Colombia", ubicado en el Amazonas.', 8000),
('La Chorrera', 1, 'Municipio caracterizado por su selva densa y comunidades indígenas.', 6000),
('Tarapacá', 1, 'Municipio amazónico con gran biodiversidad y comunidades tradicionales.', 4000),
('Puerto Santander', 1, 'Pequeño municipio en el Amazonas con gran riqueza natural.', 2000),
('La Pedrera', 1, 'Ubicado cerca de la frontera con Brasil, con acceso por vía fluvial.', 3000),
('Mirití-Paraná', 1, 'Municipio amazónico mayormente selvático con pocas carreteras.', 1000),
('Puerto Arica', 1, 'Municipio remoto en la Amazonía, accesible principalmente por río.', 500),
('Puerto Alegría', 1, 'Municipio en el Amazonas caracterizado por su aislamiento y comunidades indígenas.', 1500),
('Puerto Santander', 1, 'Municipio rural con una economía basada en la pesca y agricultura.', 1200);
-- Inserción de municipios para el departamento de Antioquia (ajusta el departamento_id según el ID real en la base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Medellín', 2, 'Capital de Antioquia y una de las ciudades principales de Colombia.', 2500000),
('Bello', 2, 'Importante municipio metropolitano de Antioquia, cercano a Medellín.', 500000),
('Itagüí', 2, 'Municipio industrial en el área metropolitana de Medellín.', 300000),
('Envigado', 2, 'Municipio en el Valle de Aburrá, conocido por su alta calidad de vida.', 230000),
('Rionegro', 2, 'Municipio ubicado en el Oriente antioqueño, con crecimiento industrial.', 150000),
('Apartadó', 2, 'Principal centro bananero de la región de Urabá.', 100000),
('Turbo', 2, 'Puerto y centro comercial en la región de Urabá.', 90000),
('Copacabana', 2, 'Municipio en el área metropolitana de Medellín.', 80000),
('La Ceja', 2, 'Municipio agrícola ubicado en el Oriente antioqueño.', 60000),
('Caucasia', 2, 'Centro comercial y minero en la región del Bajo Cauca.', 100000),
('El Carmen de Viboral', 2, 'Conocido por su producción de cerámica artesanal.', 55000),
('Santa Fe de Antioquia', 2, 'Antigua capital de Antioquia, de importancia histórica y turística.', 25000),
('Sabaneta', 2, 'Municipio pequeño pero densamente poblado, parte del área metropolitana de Medellín.', 70000),
('Jardín', 2, 'Pueblo turístico en el suroeste de Antioquia, con arquitectura colonial.', 14000),
('Guatapé', 2, 'Famoso por su embalse y su piedra natural, uno de los destinos turísticos más importantes.', 8000),
('Marinilla', 2, 'Municipio cultural en el Oriente antioqueño.', 40000),
('San Pedro de Urabá', 2, 'Municipio agrícola en la región de Urabá.', 20000),
('Amagá', 2, 'Municipio con economía basada en la minería y agricultura.', 30000),
('Caldas', 2, 'Municipio en el área metropolitana de Medellín, conocido por su industria.', 70000),
('La Estrella', 2, 'Municipio cercano a Medellín, con una economía diversificada.', 60000);
-- Inserción de municipios para el departamento de Arauca (ajusta el departamento_id según el ID real en la base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Arauca', 3, 'Capital del departamento de Arauca, ubicada en la frontera con Venezuela.', 85000),
('Arauquita', 3, 'Municipio agrícola y petrolero en la región de Arauca.', 45000),
('Cravo Norte', 3, 'Municipio en Arauca, conocido por su economía ganadera y pesquera.', 9000),
('Fortul', 3, 'Municipio en Arauca, con economía basada en la agricultura y petróleo.', 18000),
('Puerto Rondón', 3, 'Municipio ganadero ubicado en la región central de Arauca.', 6000),
('Saravena', 3, 'Municipio importante por su economía petrolera y agrícola.', 42000),
('Tame', 3, 'Municipio histórico en Arauca, conocido por su ganadería y agricultura.', 31000);
-- Inserción de municipios para el departamento de Atlántico (ajusta el departamento_id según el ID real en la base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Barranquilla', 4, 'Capital del departamento del Atlántico, principal centro urbano y portuario de la región Caribe.', 1200000),
('Baranoa', 4, 'Municipio agrícola y cultural, conocido por sus carnavales.', 60000),
('Campo de la Cruz', 4, 'Municipio en la ribera del río Magdalena, con economía agrícola.', 15000),
('Candelaria', 4, 'Pequeño municipio ubicado en el sur del Atlántico.', 13000),
('Galapa', 4, 'Municipio cercano a Barranquilla, conocido por sus artesanías y carnaval.', 30000),
('Juan de Acosta', 4, 'Municipio turístico en la costa atlántica, conocido por sus playas.', 20000),
('Luruaco', 4, 'Municipio agrícola conocido por la famosa arepa de huevo.', 25000),
('Malambo', 4, 'Municipio industrial y residencial en el área metropolitana de Barranquilla.', 125000),
('Manatí', 4, 'Municipio agrícola en la región sur del Atlántico.', 16000),
('Palmar de Varela', 4, 'Municipio en la ribera del río Magdalena, con economía basada en agricultura y ganadería.', 22000),
('Piojó', 4, 'Municipio pequeño y turístico ubicado cerca de la costa.', 8000),
('Polonuevo', 4, 'Municipio agrícola cercano a Barranquilla.', 17000),
('Ponedera', 4, 'Municipio en la región suroriental del Atlántico, con economía agrícola.', 18000),
('Puerto Colombia', 4, 'Municipio turístico en la costa atlántica, famoso por su histórico muelle.', 50000),
('Repelón', 4, 'Municipio con gran producción agrícola, conocido por su embalse.', 27000),
('Sabanagrande', 4, 'Municipio agrícola en el centro del Atlántico.', 33000),
('Sabanalarga', 4, 'Uno de los municipios más grandes del Atlántico, con economía diversificada.', 90000),
('Santa Lucía', 4, 'Municipio en el sur del Atlántico, conocido por sus festividades y tradiciones culturales.', 11000),
('Santo Tomás', 4, 'Municipio conocido por sus celebraciones de Carnaval y economía agrícola.', 30000),
('Soledad', 4, 'Municipio más poblado después de Barranquilla, parte del área metropolitana.', 700000),
('Suan', 4, 'Pequeño municipio en el sur del Atlántico, con economía ganadera y agrícola.', 10000),
('Tubará', 4, 'Municipio turístico y agrícola en la región montañosa del Atlántico.', 10000),
('Usiacurí', 4, 'Municipio conocido por sus artesanías y aguas termales.', 10000);
-- Inserción de municipios para el departamento de Bolívar (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Cartagena', 5, 'Capital de Bolívar, reconocida por su patrimonio histórico y turístico.', 1000000),
('Magangué', 5, 'Importante centro comercial y agrícola en Bolívar, ubicado a orillas del río Magdalena.', 130000),
('Turbaco', 5, 'Municipio cercano a Cartagena, conocido por su historia y clima agradable.', 60000),
('Arjona', 5, 'Municipio con economía basada en la agricultura y ganadería.', 50000),
('El Carmen de Bolívar', 5, 'Municipio en los Montes de María, importante productor de tabaco y yuca.', 70000),
('Turbana', 5, 'Municipio cercano a Cartagena con economía agrícola.', 12000),
('San Juan Nepomuceno', 5, 'Municipio en los Montes de María, conocido por su producción agrícola.', 25000),
('Villanueva', 5, 'Municipio agrícola y ganadero, ubicado en el norte de Bolívar.', 15000),
('Santa Rosa', 5, 'Municipio con fuerte tradición agrícola en el norte de Bolívar.', 11000),
('Santa Catalina', 5, 'Municipio turístico cercano a Cartagena, conocido por sus playas.', 9000),
('María La Baja', 5, 'Municipio en Bolívar, destacado por sus cultivos de arroz y palma de aceite.', 35000),
('Calamar', 5, 'Municipio portuario en el río Magdalena, con economía basada en la pesca y agricultura.', 20000),
('Cicuco', 5, 'Municipio en la región de la Depresión Momposina.', 8000),
('Córdoba', 5, 'Municipio conocido por su economía agrícola y pesca.', 10000),
('Mahates', 5, 'Municipio en los Montes de María, conocido por sus tradiciones culturales.', 14000),
('San Jacinto', 5, 'Famoso por sus artesanías, especialmente sus hamacas.', 20000),
('San Martín de Loba', 5, 'Municipio en el sur de Bolívar, con economía agrícola y minera.', 15000),
('Arenal', 5, 'Municipio con tradición minera y agrícola.', 7000),
('Hatillo de Loba', 5, 'Municipio ubicado en el sur de Bolívar, con economía agrícola.', 6000),
('Barranco de Loba', 5, 'Municipio minero y agrícola en el sur de Bolívar.', 11000),
('Altos del Rosario', 5, 'Municipio agrícola en el sur de Bolívar.', 5000),
('San Fernando', 5, 'Municipio en la región de la Depresión Momposina.', 8000),
('Montecristo', 5, 'Municipio minero en el sur de Bolívar.', 7000),
('Pinillos', 5, 'Municipio ribereño en el sur de Bolívar, con economía basada en la agricultura.', 10000),
('Regidor', 5, 'Municipio pequeño en el sur de Bolívar, con economía agrícola.', 5000),
('Río Viejo', 5, 'Municipio en el sur de Bolívar, con actividades agrícolas y pesqueras.', 6000),
('San Pablo', 5, 'Municipio agrícola y ganadero en el sur de Bolívar.', 25000),
('Simití', 5, 'Municipio en el sur de Bolívar, con actividades mineras y agrícolas.', 15000),
('Santa Rosa del Sur', 5, 'Municipio minero en el sur de Bolívar.', 20000),
('Tiquisio', 5, 'Municipio agrícola y minero en el sur de Bolívar.', 9000),
('Zambrano', 5, 'Municipio en el norte de Bolívar, con economía agrícola.', 11000);
-- Inserción de municipios para el departamento de Boyacá (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Tunja', 6, 'Capital de Boyacá, conocida por su importancia histórica en la independencia de Colombia.', 180000),
('Duitama', 6, 'Municipio industrial y comercial, conocido como la "Perla de Boyacá".', 130000),
('Sogamoso', 6, 'Centro industrial y comercial, conocido como la "Ciudad del Sol y del Acero".', 120000),
('Chiquinquirá', 6, 'Municipio religioso y turístico, famoso por su basílica.', 70000),
('Villa de Leyva', 6, 'Municipio colonial y turístico, famoso por su arquitectura y festivales.', 12000),
('Paipa', 6, 'Municipio turístico, conocido por sus termales y el lago Sochagota.', 30000),
('Samacá', 6, 'Municipio agrícola, con producción de papa y carbón.', 22000),
('Moniquirá', 6, 'Municipio conocido por la producción de bocadillo veleño y otros dulces típicos.', 21000),
('Sáchica', 6, 'Municipio turístico cerca de Villa de Leyva, famoso por sus festivales religiosos.', 5000),
('Tibasosa', 6, 'Conocido por su festival del Feijoa y su arquitectura colonial.', 8000),
('Nobsa', 6, 'Municipio artesanal, famoso por la elaboración de ruanas.', 15000),
('Soracá', 6, 'Municipio cercano a Tunja, con economía basada en la agricultura.', 4000),
('Cómbita', 6, 'Municipio agrícola, conocido por sus paisajes montañosos.', 13000),
('Aquitania', 6, 'Municipio donde se encuentra la Laguna de Tota, uno de los atractivos turísticos de Boyacá.', 15000),
('Miraflores', 6, 'Municipio agrícola con producción de café y caña de azúcar.', 10000),
('Garagoa', 6, 'Municipio en la región del Valle de Tenza, con economía agrícola.', 12000),
('Chivor', 6, 'Municipio conocido por sus minas de esmeraldas.', 3000),
('Santa Rosa de Viterbo', 6, 'Municipio de clima templado, conocido por su arquitectura colonial.', 10000),
('Soatá', 6, 'Municipio en el norte de Boyacá, con economía agrícola.', 10000),
('Tópaga', 6, 'Municipio con economía minera y agrícola.', 6000),
('Monguí', 6, 'Municipio artesanal y turístico, famoso por la elaboración de balones.', 6000),
('Ráquira', 6, 'Municipio artesanal conocido por su producción de cerámica.', 8000),
('Firavitoba', 6, 'Municipio agrícola y ganadero en el altiplano boyacense.', 4000),
('Tenza', 6, 'Municipio en el Valle de Tenza, con festivales culturales tradicionales.', 3000),
('El Cocuy', 6, 'Municipio montañoso, famoso por el Parque Nacional Natural El Cocuy.', 5000),
('Berbeo', 6, 'Municipio pequeño con economía agrícola en el sur de Boyacá.', 2000),
('Susacón', 6, 'Municipio agrícola y ganadero en la región norte de Boyacá.', 3000),
('Guateque', 6, 'Municipio en el Valle de Tenza, con economía basada en agricultura y comercio.', 7000),
('Tununguá', 6, 'Municipio pequeño en Boyacá, con economía agrícola.', 2000),
('La Uvita', 6, 'Municipio agrícola y ganadero en la región montañosa de Boyacá.', 3000),
('Cerinza', 6, 'Municipio agrícola y artesanal, con producción de caña de azúcar.', 4000),
('Paz de Río', 6, 'Municipio minero, con reservas de carbón y hierro.', 5000),
('Umbita', 6, 'Municipio en el Valle de Tenza, conocido por sus festividades religiosas.', 6000),
('San Mateo', 6, 'Municipio ganadero en el norte de Boyacá.', 3000),
('Sora', 6, 'Municipio pequeño con economía agrícola en el centro de Boyacá.', 1000),
('Otanche', 6, 'Municipio minero, famoso por sus yacimientos de esmeraldas.', 6000);
-- Inserción de municipios para el departamento de Caldas (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Manizales', 7, 'Capital del departamento de Caldas, conocida por su actividad cafetera y universitaria.', 400000),
('Aguadas', 7, 'Municipio famoso por sus sombreros y su arquitectura colonial.', 22000),
('Anserma', 7, 'Municipio agrícola, conocido como la "Abuela de Caldas".', 30000),
('Aranzazu', 7, 'Municipio caficultor, con paisajes montañosos y clima fresco.', 12000),
('Belalcázar', 7, 'Municipio ubicado en la zona cafetera, con una gran estatua de Cristo Rey.', 9000),
('Chinchiná', 7, 'Municipio cafetero y turístico, parte del Paisaje Cultural Cafetero.', 45000),
('Filadelfia', 7, 'Municipio agrícola en las montañas de Caldas.', 10000),
('La Dorada', 7, 'Municipio en el oriente de Caldas, a orillas del río Magdalena.', 78000),
('La Merced', 7, 'Municipio pequeño en el norte de Caldas, con economía cafetera.', 5000),
('Manzanares', 7, 'Municipio agrícola y caficultor en el oriente de Caldas.', 15000),
('Marmato', 7, 'Municipio minero, conocido por sus yacimientos de oro.', 9000),
('Marquetalia', 7, 'Municipio agrícola, conocido por su historia de resistencia campesina.', 12000),
('Marulanda', 7, 'Municipio rural con economía basada en la ganadería y la agricultura.', 3000),
('Neira', 7, 'Municipio cafetero, con arquitectura colonial.', 20000),
('Norcasia', 7, 'Municipio en el oriente de Caldas, cercano al río La Miel.', 6000),
('Pácora', 7, 'Municipio montañoso, conocido por su arquitectura y tradición cafetera.', 13000),
('Palestina', 7, 'Municipio donde se encuentra el Aeropuerto Internacional de Manizales.', 11000),
('Pensilvania', 7, 'Municipio agrícola y ganadero, con tradición cafetera.', 22000),
('Riosucio', 7, 'Municipio conocido por el Carnaval del Diablo y su riqueza cultural.', 26000),
('Risaralda', 7, 'Municipio pequeño en el occidente de Caldas, con economía agrícola.', 4000),
('Salamina', 7, 'Municipio histórico y turístico, conocido por su arquitectura y cultura cafetera.', 18000),
('Samaná', 7, 'Municipio cafetero en el oriente de Caldas, con paisaje montañoso.', 15000),
('San José', 7, 'Municipio pequeño con economía agrícola en el occidente de Caldas.', 6000),
('Supía', 7, 'Municipio minero y agrícola, conocido por su cultura y tradición.', 25000),
('Victoria', 7, 'Municipio en el oriente de Caldas, con economía basada en la ganadería y la agricultura.', 10000),
('Villamaría', 7, 'Municipio cercano a Manizales, con atractivos naturales y termales.', 55000),
('Viterbo', 7, 'Municipio turístico conocido por sus paisajes y clima cálido.', 10000);
-- Inserción de municipios para el departamento de Caquetá (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Florencia', 8, 'Capital del departamento de Caquetá, con economía basada en el comercio y ganadería.', 180000),
('Albania', 8, 'Municipio en el norte de Caquetá, con economía agrícola.', 8000),
('Belén de los Andaquíes', 8, 'Municipio turístico rodeado de selva y ríos.', 6000),
('Cartagena del Chairá', 8, 'Municipio en la Amazonía colombiana, con actividad agrícola y ganadera.', 25000),
('Curillo', 8, 'Municipio amazónico, con riqueza natural y cultural.', 10000),
('El Doncello', 8, 'Municipio agrícola en el norte de Caquetá.', 17000),
('El Paujil', 8, 'Municipio con economía basada en la agricultura y ganadería.', 14000),
('La Montañita', 8, 'Municipio rural con economía agrícola en el Caquetá.', 11000),
('Milán', 8, 'Municipio pequeño en el sur de Caquetá, rodeado de selva.', 5000),
('Morelia', 8, 'Municipio rural en el sur de Caquetá, con economía agrícola.', 4000),
('Puerto Rico', 8, 'Municipio amazónico con actividad agrícola y ganadera.', 20000),
('San José del Fragua', 8, 'Municipio turístico en la Amazonía, conocido por su biodiversidad.', 7000),
('San Vicente del Caguán', 8, 'Municipio grande en Caquetá, con economía basada en la agricultura y ganadería.', 40000),
('Solano', 8, 'Municipio en la Amazonía, con gran extensión de selva y baja densidad poblacional.', 10000),
('Solita', 8, 'Municipio rural en el sur de Caquetá, con actividad agrícola.', 3000),
('Valparaíso', 8, 'Municipio pequeño en la región amazónica, con economía agrícola.', 4000);
-- Inserción de municipios para el departamento de Casanare (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Yopal', 9, 'Capital del departamento de Casanare, con economía basada en el petróleo y la ganadería.', 150000),
('Aguazul', 9, 'Municipio importante por su actividad petrolera y ganadera.', 35000),
('Chámeza', 9, 'Municipio pequeño con economía basada en la agricultura y ganadería.', 3000),
('Hato Corozal', 9, 'Municipio ganadero en la región de los Llanos Orientales.', 10000),
('La Salina', 9, 'Municipio conocido por sus salinas y actividades agrícolas.', 2000),
('Maní', 9, 'Municipio ganadero y agrícola, conocido por sus paisajes llaneros.', 11000),
('Monterrey', 9, 'Municipio turístico con fuentes termales y actividades ganaderas.', 18000),
('Nunchía', 9, 'Municipio agrícola en la región de los Llanos Orientales.', 7000),
('Orocué', 9, 'Municipio ribereño en el río Meta, con actividades ganaderas y pesqueras.', 8000),
('Paz de Ariporo', 9, 'Municipio ganadero, uno de los más grandes de Casanare.', 25000),
('Pore', 9, 'Municipio histórico y turístico, antiguo centro de comercio colonial.', 6000),
('Recetor', 9, 'Municipio pequeño con economía basada en la agricultura.', 2000),
('Sabanalarga', 9, 'Municipio agrícola y ganadero en el sur de Casanare.', 5000),
('Sácama', 9, 'Municipio en la región montañosa, con economía agrícola.', 1000),
('San Luis de Palenque', 9, 'Municipio ganadero y agrícola, con eventos de cultura llanera.', 7000),
('Támara', 9, 'Municipio en la región montañosa, con agricultura y ganadería.', 4000),
('Tauramena', 9, 'Municipio con actividad petrolera y ganadera.', 18000),
('Trinidad', 9, 'Municipio en los Llanos Orientales, con economía ganadera.', 9000),
('Villanueva', 9, 'Municipio ganadero y agrícola en Casanare.', 25000);
-- Inserción de municipios para el departamento de Cauca (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Popayán', 10, 'Capital del departamento de Cauca, conocida por su arquitectura colonial.', 300000),
('Almaguer', 10, 'Municipio montañoso con economía agrícola.', 7000),
('Argelia', 10, 'Municipio en la cordillera occidental, con economía agrícola.', 9000),
('Balboa', 10, 'Municipio con economía basada en la agricultura y la ganadería.', 8000),
('Bolívar', 10, 'Municipio cafetero ubicado en el sur de Cauca.', 12000),
('Buenos Aires', 10, 'Municipio en el norte de Cauca, con actividad minera y agrícola.', 15000),
('Cajibío', 10, 'Municipio agrícola cercano a Popayán.', 10000),
('Caldono', 10, 'Municipio con alta presencia de comunidades indígenas.', 14000),
('Caloto', 10, 'Municipio agrícola y ganadero, conocido por su tradición indígena.', 17000),
('Corinto', 10, 'Municipio productor de caña de azúcar y café.', 20000),
('El Tambo', 10, 'Municipio agrícola con una economía basada en el café y el maíz.', 13000),
('Florencia', 10, 'Municipio rural con economía agrícola.', 5000),
('Guapi', 10, 'Municipio costero en el océano Pacífico, con economía pesquera.', 20000),
('Inzá', 10, 'Municipio montañoso en la cordillera central, con economía cafetera.', 8000),
('Jambaló', 10, 'Municipio indígena con actividades agrícolas.', 7000),
('La Sierra', 10, 'Municipio agrícola en el macizo colombiano.', 6000),
('La Vega', 10, 'Municipio agrícola, productor de café y caña de azúcar.', 10000),
('López de Micay', 10, 'Municipio en la costa pacífica, con economía pesquera.', 12000),
('Mercaderes', 10, 'Municipio agrícola ubicado en el sur del Cauca.', 10000),
('Miranda', 10, 'Municipio agrícola, productor de caña y café.', 18000),
('Morales', 10, 'Municipio en el norte de Cauca, con economía minera y agrícola.', 15000),
('Padilla', 10, 'Municipio en la región norte del Cauca, productor de caña de azúcar.', 5000),
('Páez', 10, 'Municipio indígena, conocido por el Parque Nacional Natural Nevado del Huila.', 9000),
('Patía', 10, 'Municipio ubicado en el Valle del Patía, con economía agrícola.', 20000),
('Piamonte', 10, 'Municipio en la región amazónica de Cauca, con actividad agrícola.', 3000),
('Piendamó', 10, 'Municipio productor de café, cercano a Popayán.', 17000),
('Puerto Tejada', 10, 'Municipio industrial y agrícola, en el norte de Cauca.', 30000),
('Puracé', 10, 'Municipio con atractivos naturales como el Volcán Puracé.', 8000),
('Rosas', 10, 'Municipio agrícola en la región sur de Cauca.', 7000),
('San Sebastián', 10, 'Municipio montañoso con actividad agrícola.', 4000),
('Santa Rosa', 10, 'Municipio pequeño y agrícola.', 3000),
('Santander de Quilichao', 10, 'Municipio industrial y comercial en el norte de Cauca.', 40000),
('Silvia', 10, 'Municipio turístico, con una gran comunidad indígena Misak.', 15000),
('Sotará', 10, 'Municipio montañoso con economía agrícola.', 5000),
('Suárez', 10, 'Municipio en el norte de Cauca, con actividad minera.', 11000),
('Sucre', 10, 'Municipio agrícola en el suroccidente de Cauca.', 6000),
('Timbío', 10, 'Municipio cafetero y agrícola cercano a Popayán.', 13000),
('Timbiquí', 10, 'Municipio en la costa pacífica, con economía pesquera y minera.', 20000),
('Toribío', 10, 'Municipio indígena con fuerte tradición cultural.', 13000),
('Totoró', 10, 'Municipio montañoso en la cordillera central.', 7000),
('Villa Rica', 10, 'Municipio industrial y agrícola en el norte de Cauca.', 20000);
-- Inserción de municipios para el departamento de Cesar (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Valledupar', 11, 'Capital del departamento de Cesar, conocida por ser la cuna del vallenato.', 500000),
('Aguachica', 11, 'Municipio importante por su ubicación comercial en la región.', 100000),
('Agustín Codazzi', 11, 'Municipio agrícola y productor de carbón.', 70000),
('Astrea', 11, 'Municipio agrícola en el centro del Cesar.', 12000),
('Becerril', 11, 'Municipio minero y agrícola en el Cesar.', 20000),
('Bosconia', 11, 'Municipio estratégico para el comercio, conocido por su economía ganadera.', 45000),
('Chimichagua', 11, 'Municipio ribereño en la Ciénaga de Zapatosa, con economía pesquera y agrícola.', 30000),
('Chiriguaná', 11, 'Municipio minero y agrícola en el Cesar.', 25000),
('Curumaní', 11, 'Municipio con una economía basada en la agricultura y ganadería.', 20000),
('El Copey', 11, 'Municipio agrícola y ganadero en el norte del Cesar.', 25000),
('El Paso', 11, 'Municipio minero y agrícola, con economía ganadera.', 15000),
('Gamarra', 11, 'Municipio ribereño del río Magdalena, con economía pesquera.', 10000),
('González', 11, 'Municipio pequeño con economía agrícola.', 6000),
('La Gloria', 11, 'Municipio en el sur del Cesar, con economía agrícola y pesquera.', 15000),
('La Jagua de Ibirico', 11, 'Municipio minero, conocido por su producción de carbón.', 30000),
('Manaure Balcón del Cesar', 11, 'Municipio turístico en la región montañosa del Cesar.', 8000),
('Pailitas', 11, 'Municipio agrícola en el sur del Cesar.', 13000),
('Pelaya', 11, 'Municipio agrícola y ganadero en el Cesar.', 12000),
('Pueblo Bello', 11, 'Municipio turístico en la Sierra Nevada de Santa Marta.', 10000),
('Río de Oro', 11, 'Municipio agrícola en el sur del Cesar.', 7000),
('San Alberto', 11, 'Municipio agrícola y comercial en la región del Cesar.', 15000),
('San Diego', 11, 'Municipio con economía agrícola y ganadera.', 11000),
('San Martín', 11, 'Municipio agrícola, uno de los más antiguos del departamento.', 20000),
('Tamalameque', 11, 'Municipio ribereño en el río Magdalena, con economía agrícola y pesquera.', 10000);
-- Inserción de municipios para el departamento de Chocó (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Quibdó', 12, 'Capital del departamento de Chocó, ubicada a orillas del río Atrato.', 130000),
('Acandí', 12, 'Municipio turístico en la costa del Caribe, conocido por sus playas.', 12000),
('Alto Baudó', 12, 'Municipio en la región selvática, con economía basada en la pesca.', 15000),
('Atrato', 12, 'Municipio en el centro de Chocó, con economía agrícola.', 5000),
('Bagadó', 12, 'Municipio minero y agrícola, en la región central del Chocó.', 8000),
('Bahía Solano', 12, 'Municipio turístico en la costa del Pacífico, conocido por el avistamiento de ballenas.', 10000),
('Bajo Baudó', 12, 'Municipio costero en el Pacífico, con economía pesquera y agrícola.', 7000),
('Bojayá', 12, 'Municipio ribereño en el río Atrato, con historia de conflictos y resiliencia.', 11000),
('Cantón de San Pablo', 12, 'Municipio rural, conocido por sus ríos y selvas.', 4000),
('Carmen del Darién', 12, 'Municipio ubicado en la región del Darién, con economía agrícola.', 6000),
('Cértegui', 12, 'Municipio minero y agrícola en el Chocó.', 4000),
('Condoto', 12, 'Municipio minero, conocido por sus yacimientos de oro y platino.', 12000),
('El Carmen de Atrato', 12, 'Municipio agrícola en la región montañosa de Chocó.', 10000),
('El Litoral del San Juan', 12, 'Municipio costero en el Pacífico, con economía pesquera.', 9000),
('Istmina', 12, 'Municipio comercial y minero, uno de los principales del Chocó.', 20000),
('Juradó', 12, 'Municipio costero en el Pacífico, cercano a la frontera con Panamá.', 5000),
('Lloró', 12, 'Municipio con alta pluviosidad, conocido por ser una de las zonas más lluviosas del mundo.', 3000),
('Medio Atrato', 12, 'Municipio rural con economía basada en la agricultura y la pesca.', 8000),
('Medio Baudó', 12, 'Municipio selvático, con una economía agrícola y pesquera.', 7000),
('Medio San Juan', 12, 'Municipio ribereño en el río San Juan, con economía agrícola.', 6000),
('Nóvita', 12, 'Municipio minero en la región central del Chocó.', 8000),
('Nuquí', 12, 'Municipio turístico en la costa pacífica, famoso por el ecoturismo y el avistamiento de ballenas.', 8000),
('Río Iró', 12, 'Municipio en el centro del Chocó, con economía agrícola.', 5000),
('Río Quito', 12, 'Municipio en la región selvática, con economía basada en la minería y la agricultura.', 7000),
('Riosucio', 12, 'Municipio en la región del Darién, conocido por su biodiversidad.', 10000),
('San José del Palmar', 12, 'Municipio montañoso con economía agrícola.', 4000),
('Sipí', 12, 'Municipio pequeño en el Chocó, con economía agrícola y pesquera.', 3000),
('Tadó', 12, 'Municipio minero y agrícola en el centro del Chocó.', 10000),
('Unguía', 12, 'Municipio en la región del Darién, cerca de la frontera con Panamá.', 8000),
('Unión Panamericana', 12, 'Municipio rural en el Chocó, con economía agrícola.', 5000);
-- Inserción de municipios para el departamento de Córdoba (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Montería', 13, 'Capital de Córdoba, conocida como la "Perla del Sinú".', 500000),
('Ayapel', 13, 'Municipio ribereño en el río San Jorge, con economía pesquera.', 25000),
('Buenavista', 13, 'Municipio agrícola en el sur de Córdoba.', 12000),
('Canalete', 13, 'Municipio pequeño en la costa, con economía basada en la agricultura.', 8000),
('Cereté', 13, 'Municipio en el valle del Sinú, con economía agrícola y ganadera.', 85000),
('Chimá', 13, 'Municipio agrícola en el norte de Córdoba.', 10000),
('Chinú', 13, 'Municipio en el valle del Sinú, con producción agrícola.', 40000),
('Ciénaga de Oro', 13, 'Municipio reconocido por sus festivales y actividades agrícolas.', 30000),
('Cotorra', 13, 'Municipio pequeño en el norte de Córdoba.', 10000),
('La Apartada', 13, 'Municipio minero y agrícola en el sur de Córdoba.', 15000),
('Lorica', 13, 'Municipio histórico y turístico, famoso por su arquitectura colonial.', 100000),
('Los Córdobas', 13, 'Municipio costero con economía basada en la agricultura.', 9000),
('Momil', 13, 'Municipio pequeño en el norte de Córdoba, con economía agrícola.', 7000),
('Montelíbano', 13, 'Municipio minero, conocido por la producción de níquel.', 80000),
('Moñitos', 13, 'Municipio costero en el mar Caribe, con economía pesquera.', 12000),
('Planeta Rica', 13, 'Municipio con economía agrícola y ganadera.', 50000),
('Pueblo Nuevo', 13, 'Municipio agrícola en el valle del Sinú.', 20000),
('Puerto Escondido', 13, 'Municipio costero con economía pesquera y turística.', 15000),
('Puerto Libertador', 13, 'Municipio minero en el sur de Córdoba.', 25000),
('Purísima', 13, 'Municipio pequeño en el norte de Córdoba, con tradición cultural.', 8000),
('Sahagún', 13, 'Municipio importante en Córdoba, conocido por su actividad agrícola.', 90000),
('San Andrés de Sotavento', 13, 'Municipio en el norte de Córdoba, famoso por su artesanía de sombreros vueltiaos.', 20000),
('San Antero', 13, 'Municipio costero conocido por sus festividades de burros.', 18000),
('San Bernardo del Viento', 13, 'Municipio turístico en la costa del Caribe.', 15000),
('San Carlos', 13, 'Municipio agrícola en el valle del Sinú.', 20000),
('San Pelayo', 13, 'Municipio conocido por el Festival Nacional del Porro.', 15000),
('Tierralta', 13, 'Municipio en el sur de Córdoba, con actividad agrícola y ganadera.', 60000),
('Tuchín', 13, 'Municipio artesanal, famoso por la fabricación de sombreros vueltiaos.', 10000),
('Valencia', 13, 'Municipio agrícola en el valle del Sinú.', 25000);
-- Inserción de municipios para el departamento de Cundinamarca (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Bogotá', 14, 'Capital de Colombia y del departamento de Cundinamarca.', 7800000),
('Agua de Dios', 14, 'Municipio turístico y residencial en Cundinamarca.', 15000),
('Albán', 14, 'Municipio agrícola y turístico en las montañas de Cundinamarca.', 8000),
('Anapoima', 14, 'Municipio turístico conocido por su clima cálido.', 12000),
('Anolaima', 14, 'Municipio agrícola, productor de frutas como la guayaba.', 10000),
('Apulo', 14, 'Municipio turístico y agrícola en el valle del río Apulo.', 7000),
('Arbeláez', 14, 'Municipio conocido por su producción agrícola y actividades turísticas.', 9000),
('Beltrán', 14, 'Pequeño municipio agrícola en el valle del Magdalena.', 3000),
('Bituima', 14, 'Municipio montañoso con economía basada en la agricultura.', 4000),
('Bojacá', 14, 'Municipio agrícola cercano a Bogotá, conocido por sus festividades religiosas.', 7000),
('Cabrera', 14, 'Municipio rural con economía agrícola en Cundinamarca.', 5000),
('Cachipay', 14, 'Municipio turístico, conocido por su clima agradable y cultivos de flores.', 8000),
('Cajicá', 14, 'Municipio residencial y turístico, cercano a Bogotá.', 60000),
('Caparrapí', 14, 'Municipio en el valle del Magdalena, con economía agrícola.', 10000),
('Cáqueza', 14, 'Municipio montañoso, con tradición agrícola.', 13000),
('Chaguaní', 14, 'Municipio pequeño en el valle del Magdalena.', 4000),
('Chía', 14, 'Municipio residencial y comercial, parte del área metropolitana de Bogotá.', 120000),
('Chipaque', 14, 'Municipio montañoso, con economía agrícola y ganadera.', 10000),
('Choachí', 14, 'Municipio turístico, conocido por sus aguas termales.', 12000),
('Chocontá', 14, 'Municipio agrícola, productor de papa y flores.', 18000),
('Cogua', 14, 'Municipio agrícola y minero, cercano a Zipaquirá.', 11000),
('Cota', 14, 'Municipio industrial y residencial, parte del área metropolitana de Bogotá.', 29000),
('Cucunubá', 14, 'Municipio conocido por sus artesanías en lana y tradición cultural.', 4000),
('El Colegio', 14, 'Municipio turístico y agrícola en el valle del Magdalena.', 25000),
('El Peñón', 14, 'Municipio pequeño en la región montañosa de Cundinamarca.', 3000),
('El Rosal', 14, 'Municipio agrícola e industrial, cercano a Bogotá.', 15000),
('Facatativá', 14, 'Municipio industrial y agrícola, conocido por el Parque Arqueológico de Facatativá.', 120000),
('Fómeque', 14, 'Municipio montañoso, cercano al Parque Nacional Natural Chingaza.', 11000),
('Fosca', 14, 'Municipio en la región montañosa, con economía agrícola.', 5000),
('Funza', 14, 'Municipio industrial y residencial, parte del área metropolitana de Bogotá.', 70000),
('Fúquene', 14, 'Municipio cercano a la laguna de Fúquene, con economía agrícola.', 6000),
('Fusagasugá', 14, 'Municipio turístico y agrícola, conocido por su producción de flores.', 140000),
('Gachalá', 14, 'Municipio en la región montañosa, con economía minera.', 4000),
('Gachancipá', 14, 'Municipio industrial y agrícola, cercano a Bogotá.', 6000),
('Gachetá', 14, 'Municipio en el Valle de Ubaté, con economía agrícola.', 8000),
('Gama', 14, 'Municipio pequeño en la región montañosa de Cundinamarca.', 3000),
('Girardot', 14, 'Importante centro turístico y comercial en el valle del Magdalena.', 110000),
('Granada', 14, 'Municipio agrícola en la región montañosa de Cundinamarca.', 10000),
('Guachetá', 14, 'Municipio agrícola, conocido por sus salinas.', 9000),
('Guaduas', 14, 'Municipio histórico, conocido por su arquitectura colonial.', 30000),
('Guasca', 14, 'Municipio turístico cercano al Parque Nacional Natural Chingaza.', 12000),
('Guatavita', 14, 'Municipio turístico, conocido por la Laguna de Guatavita.', 7000),
('Guayabal de Síquima', 14, 'Municipio agrícola en la región de Cundinamarca.', 4000),
('Jerusalén', 14, 'Municipio pequeño en el valle del Magdalena.', 2000),
('Junín', 14, 'Municipio montañoso con economía agrícola.', 5000),
('La Calera', 14, 'Municipio turístico y residencial, cercano a Bogotá.', 25000),
('La Mesa', 14, 'Municipio turístico y agrícola, conocido por su clima templado.', 30000),
('La Palma', 14, 'Municipio en la región montañosa de Cundinamarca.', 8000),
('La Peña', 14, 'Municipio agrícola en la región montañosa de Cundinamarca.', 6000),
('La Vega', 14, 'Municipio turístico en la región de Cundinamarca.', 20000),
('Lenguazaque', 14, 'Municipio agrícola y minero en el norte de Cundinamarca.', 6000),
('Machetá', 14, 'Municipio en la región montañosa, con economía agrícola.', 8000),
('Madrid', 14, 'Municipio industrial y residencial, parte del área metropolitana de Bogotá.', 100000),
('Manta', 14, 'Municipio pequeño en la región montañosa de Cundinamarca.', 3000),
('Medina', 14, 'Municipio en la región del piedemonte llanero.', 5000),
('Mosquera', 14, 'Municipio industrial y residencial, parte del área metropolitana de Bogotá.', 100000),
('Nariño', 14, 'Municipio agrícola en la región montañosa de Cundinamarca.', 4000),
('Nemocón', 14, 'Municipio conocido por sus minas de sal y atractivo turístico.', 11000),
('Nilo', 14, 'Municipio agrícola y turístico en el valle del Magdalena.', 8000),
('Nimaima', 14, 'Municipio turístico en la región de Cundinamarca.', 5000),
('Nocaima', 14, 'Municipio montañoso en Cundinamarca, con economía agrícola.', 6000),
('Pacho', 14, 'Municipio agrícola, conocido por su producción de cítricos.', 25000),
('Paime', 14, 'Municipio en la región montañosa de Cundinamarca.', 3000),
('San Antonio del Tequendama', 14, 'Municipio turístico, conocido por su cascada.', 15000),
('Soacha', 14, 'Municipio densamente poblado y parte del área metropolitana de Bogotá.', 600000),
('Subachoque', 14, 'Municipio agrícola y turístico cercano a Bogotá.', 10000),
('Suesca', 14, 'Municipio turístico, conocido por sus formaciones rocosas.', 7000),
('Supatá', 14, 'Municipio agrícola en la región montañosa de Cundinamarca.', 4000),
('Tabio', 14, 'Municipio agrícola y turístico, cercano a Bogotá.', 20000),
('Tausa', 14, 'Municipio agrícola en la región montañosa de Cundinamarca.', 5000),
('Tena', 14, 'Municipio turístico y agrícola en el valle del Magdalena.', 7000),
('Tocancipá', 14, 'Municipio industrial, conocido por su parque temático Jaime Duque.', 30000),
('Venecia', 14, 'Municipio pequeño en la región de Cundinamarca.', 3000),
('Vergara', 14, 'Municipio agrícola y turístico en la región montañosa.', 5000),
('Vianí', 14, 'Municipio agrícola en la región de Cundinamarca.', 4000),
('Villagómez', 14, 'Municipio pequeño en la región montañosa.', 3000),
('Villeta', 14, 'Municipio turístico y productor de panela.', 25000),
('Zipacón', 14, 'Municipio agrícola y turístico cercano a Bogotá.', 5000),
('Zipaquirá', 14, 'Municipio turístico, famoso por su Catedral de Sal.', 100000);
-- Inserción de municipios para el departamento de Guainía (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Inírida', 15, 'Capital del departamento de Guainía, ubicada en la Amazonía colombiana.', 15000),
('Barrancominas', 15, 'Municipio recientemente creado, con economía basada en la minería y la agricultura.', 6000),
('Cacahual', 15, 'Corregimiento en la región amazónica, de baja densidad poblacional.', 2000),
('La Guadalupe', 15, 'Corregimiento en la región de Guainía, con economía agrícola.', 1500),
('Mapiripana', 15, 'Corregimiento en la región amazónica, de economía rural y agrícola.', 1000),
('Morichal', 15, 'Corregimiento en el departamento de Guainía, con actividades agrícolas.', 1200),
('Pana Pana', 15, 'Corregimiento en Guainía, con una población mayormente indígena.', 800),
('Puerto Colombia', 15, 'Corregimiento ubicado en la región de Guainía, con economía basada en la pesca y la agricultura.', 1800),
('San Felipe', 15, 'Corregimiento en la Amazonía, con una pequeña población y economía rural.', 1000);
-- Inserción de municipios para el departamento de Guaviare (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('San José del Guaviare', 16, 'Capital del departamento de Guaviare, ubicada en la región amazónica.', 49000),
('Calamar', 16, 'Municipio en la región amazónica, con economía agrícola y ganadera.', 10000),
('El Retorno', 16, 'Municipio agrícola en Guaviare, con actividades de ganadería y agricultura.', 8000),
('Miraflores', 16, 'Municipio en la Amazonía colombiana, con una población mayormente indígena.', 5000);
-- Inserción de municipios para el departamento de Huila (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Neiva', 17, 'Capital del departamento de Huila, conocida por sus festivales folclóricos.', 350000),
('Acevedo', 17, 'Municipio agrícola, productor de café y frutas.', 20000),
('Agrado', 17, 'Municipio pequeño con economía basada en la agricultura.', 8000),
('Aipe', 17, 'Municipio con economía agrícola, conocido por sus termales.', 12000),
('Algeciras', 17, 'Municipio agrícola, con producción de café y caña de azúcar.', 15000),
('Altamira', 17, 'Municipio con economía agrícola en el sur de Huila.', 5000),
('Baraya', 17, 'Municipio agrícola, cercano al Parque Nacional Natural Nevado del Huila.', 7000),
('Campoalegre', 17, 'Municipio agrícola, productor de arroz y frutas.', 25000),
('Colombia', 17, 'Municipio en el norte de Huila, con economía agrícola.', 6000),
('Elías', 17, 'Municipio pequeño en el sur de Huila, con economía agrícola.', 4000),
('Garzón', 17, 'Importante centro comercial y agrícola en el centro de Huila.', 80000),
('Gigante', 17, 'Municipio conocido por su producción de café y frutas.', 18000),
('Guadalupe', 17, 'Municipio agrícola, productor de café y cacao.', 10000),
('Hobo', 17, 'Municipio pequeño con economía agrícola en el valle del Magdalena.', 6000),
('Iquira', 17, 'Municipio agrícola en la región montañosa de Huila.', 4000),
('Isnos', 17, 'Municipio turístico, conocido por los restos arqueológicos de San Agustín.', 10000),
('La Argentina', 17, 'Municipio en el occidente de Huila, con economía agrícola.', 8000),
('La Plata', 17, 'Municipio agrícola, importante centro comercial en el occidente de Huila.', 30000),
('Nátaga', 17, 'Municipio pequeño en el occidente de Huila, con economía agrícola.', 4000),
('Oporapa', 17, 'Municipio pequeño con economía basada en la agricultura.', 3000),
('Paicol', 17, 'Municipio turístico, conocido por sus cuevas y cavernas.', 5000),
('Palermo', 17, 'Municipio agrícola cercano a Neiva.', 20000),
('Palestina', 17, 'Municipio pequeño con economía agrícola en Huila.', 3000),
('Pital', 17, 'Municipio agrícola, productor de café y frutas.', 10000),
('Pitalito', 17, 'Importante centro agrícola y comercial, conocido por su producción de café.', 135000),
('Rivera', 17, 'Municipio turístico, famoso por sus aguas termales.', 20000),
('Saladoblanco', 17, 'Municipio pequeño en el sur de Huila, con economía agrícola.', 4000),
('San Agustín', 17, 'Municipio turístico, conocido por el Parque Arqueológico de San Agustín.', 12000),
('Santa María', 17, 'Municipio en el norte de Huila, con economía agrícola.', 5000),
('Suaza', 17, 'Municipio agrícola en el sur de Huila, productor de café y frutas.', 10000),
('Tarqui', 17, 'Municipio con economía basada en la agricultura y la ganadería.', 8000),
('Tello', 17, 'Municipio agrícola, productor de arroz y otros cultivos.', 12000),
('Teruel', 17, 'Municipio pequeño con economía agrícola en el occidente de Huila.', 7000),
('Tesalia', 17, 'Municipio agrícola en el occidente de Huila.', 5000),
('Timaná', 17, 'Municipio histórico y agrícola en el sur de Huila.', 10000),
('Villavieja', 17, 'Municipio turístico, famoso por el Desierto de la Tatacoa.', 8000),
('Yaguará', 17, 'Municipio agrícola y turístico en el occidente de Huila.', 9000);
-- Inserción de municipios para el departamento de La Guajira (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Riohacha', 18, 'Capital del departamento de La Guajira, ubicada en la costa Caribe.', 220000),
('Albania', 18, 'Municipio agrícola y ganadero, conocido por su cercanía a las minas de carbón.', 25000),
('Barrancas', 18, 'Municipio minero, cercano al complejo carbonífero de Cerrejón.', 30000),
('Dibulla', 18, 'Municipio costero en el Caribe, con economía pesquera y agrícola.', 15000),
('Distracción', 18, 'Municipio agrícola en la región de La Guajira.', 8000),
('El Molino', 18, 'Municipio agrícola y ganadero en el sur de La Guajira.', 6000),
('Fonseca', 18, 'Municipio agrícola, con una economía basada en el cultivo de frutas y ganadería.', 30000),
('Hatonuevo', 18, 'Municipio minero, cercano al complejo de carbón de Cerrejón.', 10000),
('La Jagua del Pilar', 18, 'Municipio pequeño en el sur de La Guajira, con economía agrícola.', 4000),
('Maicao', 18, 'Municipio fronterizo, conocido por su actividad comercial.', 130000),
('Manaure', 18, 'Municipio costero, famoso por su producción de sal.', 22000),
('San Juan del Cesar', 18, 'Municipio agrícola y ganadero, conocido por sus festividades culturales.', 34000),
('Uribia', 18, 'Municipio mayormente indígena, con vastas áreas desérticas y economía artesanal.', 18000),
('Urumita', 18, 'Municipio pequeño en el sur de La Guajira, con economía agrícola.', 6000),
('Villanueva', 18, 'Municipio agrícola y ganadero, conocido por sus festividades culturales.', 20000);
-- Inserción de municipios para el departamento de Magdalena (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Santa Marta', 19, 'Capital del departamento de Magdalena, ubicada en la costa Caribe.', 500000),
('Algarrobo', 19, 'Municipio agrícola en el Magdalena, con producción de frutas y cultivos.', 10000),
('Aracataca', 19, 'Municipio natal de Gabriel García Márquez, con economía agrícola y turística.', 25000),
('Ariguaní', 19, 'Municipio agrícola en el sur del Magdalena.', 15000),
('Cerro de San Antonio', 19, 'Municipio ribereño en el río Magdalena, con economía pesquera y agrícola.', 7000),
('Chibolo', 19, 'Municipio agrícola en el centro del Magdalena.', 10000),
('Ciénaga', 19, 'Municipio costero y turístico, conocido por su economía pesquera y agrícola.', 110000),
('Concordia', 19, 'Municipio en el Magdalena, con economía basada en la agricultura.', 12000),
('El Banco', 19, 'Municipio ribereño, conocido por el Festival Nacional de la Cumbia.', 50000),
('El Piñón', 19, 'Municipio agrícola en el Magdalena.', 9000),
('El Retén', 19, 'Municipio en el centro del Magdalena, con economía agrícola.', 10000),
('Fundación', 19, 'Municipio agrícola, conocido por su producción de frutas y ganadería.', 50000),
('Guamal', 19, 'Municipio en el Magdalena, con economía agrícola y pesquera.', 7000),
('Nueva Granada', 19, 'Municipio agrícola en el sur del Magdalena.', 8000),
('Pedraza', 19, 'Municipio en el Magdalena, con una economía basada en la agricultura.', 5000),
('Pijiño del Carmen', 19, 'Municipio agrícola en el sur del Magdalena.', 6000),
('Pivijay', 19, 'Municipio agrícola y ganadero, uno de los más grandes del Magdalena.', 30000),
('Plato', 19, 'Municipio agrícola y comercial en el sur del Magdalena.', 50000),
('Puebloviejo', 19, 'Municipio costero en el Caribe, conocido por su economía pesquera.', 35000),
('Remolino', 19, 'Municipio ribereño en el río Magdalena, con economía agrícola.', 9000),
('Sabanas de San Ángel', 19, 'Municipio pequeño en el Magdalena, con economía agrícola.', 7000),
('Salamina', 19, 'Municipio ribereño y agrícola, con un importante patrimonio cultural.', 15000),
('San Sebastián de Buenavista', 19, 'Municipio en el sur del Magdalena, con economía agrícola.', 10000),
('San Zenón', 19, 'Municipio en el Magdalena, con economía agrícola y pesquera.', 8000),
('Santa Ana', 19, 'Municipio agrícola en el sur del Magdalena.', 12000),
('Santa Bárbara de Pinto', 19, 'Municipio pequeño en el Magdalena, con economía agrícola.', 4000),
('Sitionuevo', 19, 'Municipio costero y agrícola, cercano a Barranquilla.', 20000),
('Tenerife', 19, 'Municipio ribereño en el río Magdalena, con economía agrícola y pesquera.', 10000),
('Zapayán', 19, 'Municipio en el Magdalena, con economía agrícola.', 5000),
('Zona Bananera', 19, 'Municipio agrícola, conocido por su producción de banano.', 45000);
-- Inserción de municipios para el departamento de Meta (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Villavicencio', 20, 'Capital del Meta, puerta de entrada a los Llanos Orientales.', 550000),
('Acacías', 20, 'Municipio turístico y agrícola, conocido por sus festividades llaneras.', 45000),
('Barranca de Upía', 20, 'Municipio pequeño con economía basada en la ganadería y la agricultura.', 7000),
('Cabuyaro', 20, 'Municipio en el Meta, con economía ganadera y agrícola.', 5000),
('Castilla La Nueva', 20, 'Municipio petrolero y agrícola en el Meta.', 15000),
('Cubarral', 20, 'Municipio en el piedemonte llanero, con producción agrícola.', 12000),
('Cumaral', 20, 'Municipio agrícola y ganadero cercano a Villavicencio.', 25000),
('El Calvario', 20, 'Municipio montañoso en el piedemonte llanero.', 3000),
('El Castillo', 20, 'Municipio agrícola y ganadero en el Meta.', 11000),
('El Dorado', 20, 'Municipio en el Meta, con economía basada en la agricultura.', 8000),
('Fuente de Oro', 20, 'Municipio agrícola, conocido por su producción de arroz.', 9000),
('Granada', 20, 'Importante centro comercial y agrícola en el Meta.', 30000),
('Guamal', 20, 'Municipio agrícola, productor de palma de aceite y otros cultivos.', 12000),
('Mapiripán', 20, 'Municipio en la región amazónica del Meta, con baja densidad poblacional.', 8000),
('Mesetas', 20, 'Municipio montañoso con economía agrícola.', 6000),
('La Macarena', 20, 'Municipio turístico, conocido por Caño Cristales.', 12000),
('La Uribe', 20, 'Municipio en el Meta, con economía basada en la agricultura.', 8000),
('Lejanías', 20, 'Municipio agrícola en el piedemonte llanero.', 10000),
('Puerto Concordia', 20, 'Municipio en la región amazónica, con economía agrícola.', 5000),
('Puerto Gaitán', 20, 'Municipio petrolero y ganadero en el Meta.', 25000),
('Puerto Lleras', 20, 'Municipio en el Meta, con economía agrícola.', 7000),
('Puerto López', 20, 'Municipio conocido como el "ombligo de Colombia".', 20000),
('Puerto Rico', 20, 'Municipio agrícola y ganadero en el Meta.', 12000),
('Restrepo', 20, 'Municipio turístico y agrícola cercano a Villavicencio.', 15000),
('San Carlos de Guaroa', 20, 'Municipio agrícola y ganadero en el Meta.', 8000),
('San Juan de Arama', 20, 'Municipio agrícola en el Meta.', 10000),
('San Martín', 20, 'Municipio histórico, conocido por sus festividades llaneras.', 20000),
('Vista Hermosa', 20, 'Municipio en el Meta, con economía agrícola.', 9000);
-- Inserción de municipios para el departamento de Nariño (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Pasto', 21, 'Capital del departamento de Nariño, conocida por su arquitectura colonial y festivales.', 400000),
('Albán', 21, 'Municipio agrícola en la región montañosa de Nariño.', 7000),
('Aldana', 21, 'Municipio en la frontera con Ecuador, con una población mayormente indígena.', 6000),
('Ancuya', 21, 'Municipio pequeño en Nariño, con economía agrícola.', 5000),
('Arboleda', 21, 'Municipio en el norte de Nariño, conocido por su producción de café.', 8000),
('Barbacoas', 21, 'Municipio en la costa del Pacífico, con economía basada en la minería y la pesca.', 20000),
('Belén', 21, 'Municipio agrícola en el norte de Nariño.', 4000),
('Buesaco', 21, 'Municipio productor de café en la región montañosa de Nariño.', 15000),
('Chachagüí', 21, 'Municipio cercano a Pasto, conocido por su aeropuerto.', 10000),
('Colón', 21, 'Municipio en Nariño, con economía basada en la agricultura.', 7000),
('Consacá', 21, 'Municipio agrícola, conocido por sus sitios históricos.', 8000),
('Contadero', 21, 'Municipio en el sur de Nariño, cercano a la frontera con Ecuador.', 7000),
('Córdoba', 21, 'Municipio agrícola, productor de papa y maíz.', 10000),
('Cuaspud', 21, 'Municipio fronterizo con Ecuador, con economía agrícola.', 7000),
('Cumbal', 21, 'Municipio conocido por el volcán Cumbal y su población indígena.', 14000),
('Cumbitara', 21, 'Municipio en la región montañosa, con economía agrícola.', 6000),
('El Charco', 21, 'Municipio costero en el Pacífico, con economía pesquera.', 15000),
('El Peñol', 21, 'Municipio pequeño en el norte de Nariño, con economía agrícola.', 5000),
('El Rosario', 21, 'Municipio agrícola en Nariño.', 7000),
('El Tablón de Gómez', 21, 'Municipio en la región montañosa de Nariño.', 5000),
('El Tambo', 21, 'Municipio agrícola, conocido por su producción de café y frutas.', 12000),
('Francisco Pizarro', 21, 'Municipio costero en el Pacífico, con economía basada en la pesca.', 8000),
('Funes', 21, 'Municipio en Nariño, con economía agrícola.', 6000),
('Guachucal', 21, 'Municipio fronterizo con Ecuador, conocido por su cultura indígena.', 9000),
('Guaitarilla', 21, 'Municipio en la región andina, con economía agrícola.', 10000),
('Gualmatán', 21, 'Municipio pequeño en el sur de Nariño, cercano a la frontera.', 4000),
('Iles', 21, 'Municipio en el sur de Nariño, conocido por su producción de maíz.', 6000),
('Imués', 21, 'Municipio pequeño en Nariño, con economía agrícola.', 5000),
('Ipiales', 21, 'Municipio fronterizo con Ecuador, conocido por el Santuario de Las Lajas.', 130000),
('La Cruz', 21, 'Municipio agrícola en el norte de Nariño.', 15000),
('La Florida', 21, 'Municipio productor de café y frutas, cercano a Pasto.', 10000),
('La Llanada', 21, 'Municipio minero en el norte de Nariño.', 3000),
('La Tola', 21, 'Municipio costero en el Pacífico, con economía pesquera.', 7000),
('La Unión', 21, 'Municipio agrícola en Nariño, conocido por su producción de café.', 20000),
('Leiva', 21, 'Municipio montañoso en Nariño, con economía agrícola.', 7000),
('Linares', 21, 'Municipio agrícola y minero en Nariño.', 6000),
('Los Andes', 21, 'Municipio en la región montañosa de Nariño.', 8000),
('Magüí', 21, 'Municipio en la región del Pacífico, con economía minera y pesquera.', 15000),
('Mallama', 21, 'Municipio pequeño en Nariño, con economía agrícola.', 4000),
('Mosquera', 21, 'Municipio costero en el Pacífico, con economía pesquera.', 10000),
('Nariño', 21, 'Municipio agrícola en el norte de Nariño.', 8000),
('Olaya Herrera', 21, 'Municipio costero en el Pacífico, con economía pesquera y agrícola.', 12000),
('Ospina', 21, 'Municipio en la región montañosa, con economía agrícola.', 6000),
('Policarpa', 21, 'Municipio en el norte de Nariño, con economía agrícola.', 7000),
('Potosí', 21, 'Municipio en el sur de Nariño, cercano a la frontera con Ecuador.', 6000),
('Providencia', 21, 'Municipio pequeño en Nariño, con economía agrícola.', 4000),
('Puerres', 21, 'Municipio en el sur de Nariño, con producción agrícola.', 5000),
('Pupiales', 21, 'Municipio en el sur de Nariño, cercano a la frontera con Ecuador.', 10000),
('Ricaurte', 21, 'Municipio en la región montañosa de Nariño.', 6000),
('Roberto Payán', 21, 'Municipio en la costa del Pacífico, con economía pesquera.', 7000),
('Samaniego', 21, 'Municipio agrícola en la región montañosa de Nariño.', 13000),
('San Bernardo', 21, 'Municipio en la región andina de Nariño, con economía agrícola.', 5000),
('San Lorenzo', 21, 'Municipio agrícola en el norte de Nariño.', 8000),
('San Pablo', 21, 'Municipio en la región montañosa, con economía agrícola.', 10000),
('San Pedro de Cartago', 21, 'Municipio pequeño en Nariño, con economía agrícola.', 3000),
('Santa Bárbara', 21, 'Municipio agrícola en Nariño.', 4000),
('Santacruz', 21, 'Municipio montañoso en Nariño.', 7000),
('Sapuyes', 21, 'Municipio en la región andina, con economía agrícola.', 5000),
('Taminango', 21, 'Municipio agrícola en Nariño.', 12000),
('Tangua', 21, 'Municipio en la región andina, cercano a Pasto.', 7000),
('Tumaco', 21, 'Municipio costero en el Pacífico, conocido por sus playas y economía pesquera.', 200000),
('Túquerres', 21, 'Municipio en la región montañosa, conocido por el volcán Azufral.', 25000),
('Yacuanquer', 21, 'Municipio montañoso en Nariño, con economía agrícola.', 6000);
-- Inserción de municipios para el departamento de Norte de Santander (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Cúcuta', 22, 'Capital del departamento de Norte de Santander, ubicada en la frontera con Venezuela.', 750000),
('Ábrego', 22, 'Municipio agrícola en Norte de Santander, conocido por su producción de café.', 20000),
('Arboledas', 22, 'Municipio agrícola en la región montañosa de Norte de Santander.', 10000),
('Bochalema', 22, 'Municipio pequeño en el departamento de Norte de Santander, con economía agrícola.', 7000),
('Bucarasica', 22, 'Municipio en el norte de Norte de Santander, con economía agrícola.', 4000),
('Cáchira', 22, 'Municipio en la región montañosa, productor de café y otros cultivos.', 6000),
('Cácota', 22, 'Municipio en la cordillera oriental, con economía agrícola.', 3000),
('Chinácota', 22, 'Municipio turístico en el norte de Norte de Santander, conocido por su clima templado.', 10000),
('Chitagá', 22, 'Municipio agrícola en la región montañosa de Norte de Santander.', 9000),
('Convención', 22, 'Municipio agrícola en el norte de Norte de Santander.', 15000),
('Cucutilla', 22, 'Municipio pequeño en Norte de Santander, con economía agrícola.', 5000),
('Durania', 22, 'Municipio agrícola en el norte de Norte de Santander.', 3000),
('El Carmen', 22, 'Municipio agrícola y minero en el norte de Norte de Santander.', 10000),
('El Tarra', 22, 'Municipio en la región del Catatumbo, con economía agrícola.', 15000),
('El Zulia', 22, 'Municipio agrícola cercano a Cúcuta.', 30000),
('Gramalote', 22, 'Municipio que fue reconstruido tras una catástrofe natural en 2010.', 6000),
('Hacarí', 22, 'Municipio en el norte de Norte de Santander, con economía agrícola.', 7000),
('Herrán', 22, 'Municipio pequeño en la cordillera oriental, con economía agrícola.', 4000),
('Labateca', 22, 'Municipio en la región montañosa de Norte de Santander.', 5000),
('La Esperanza', 22, 'Municipio agrícola en el norte de Norte de Santander.', 6000),
('La Playa', 22, 'Municipio pequeño en el norte de Norte de Santander.', 4000),
('Los Patios', 22, 'Municipio residencial e industrial, parte del área metropolitana de Cúcuta.', 120000),
('Lourdes', 22, 'Municipio agrícola en el norte de Norte de Santander.', 5000),
('Mutiscua', 22, 'Municipio en la región montañosa de Norte de Santander.', 3000),
('Ocaña', 22, 'Municipio histórico y comercial en el norte de Norte de Santander.', 100000),
('Pamplona', 22, 'Municipio universitario y turístico, conocido por su historia colonial.', 55000),
('Pamplonita', 22, 'Municipio en la región montañosa, con economía agrícola.', 4000),
('Puerto Santander', 22, 'Municipio fronterizo en el río Zulia, con economía comercial y agrícola.', 10000),
('Ragonvalia', 22, 'Municipio en la frontera con Venezuela, con economía agrícola.', 5000),
('Salazar', 22, 'Municipio agrícola en el norte de Norte de Santander.', 6000),
('San Calixto', 22, 'Municipio en la región del Catatumbo, con economía agrícola.', 8000),
('San Cayetano', 22, 'Municipio agrícola cercano a Cúcuta.', 6000),
('Santiago', 22, 'Municipio pequeño en la región montañosa de Norte de Santander.', 4000),
('Sardinata', 22, 'Municipio agrícola y ganadero en el norte de Norte de Santander.', 20000),
('Silos', 22, 'Municipio en la cordillera oriental, con clima frío y economía agrícola.', 5000),
('Teorama', 22, 'Municipio en la región del Catatumbo, con economía agrícola.', 10000),
('Tibú', 22, 'Municipio en la región del Catatumbo, con actividad petrolera y agrícola.', 40000),
('Toledo', 22, 'Municipio en la región montañosa de Norte de Santander.', 7000),
('Villa Caro', 22, 'Municipio pequeño en Norte de Santander, con economía agrícola.', 3000),
('Villa del Rosario', 22, 'Municipio histórico en la frontera con Venezuela, parte del área metropolitana de Cúcuta.', 90000);
-- Inserción de municipios para el departamento de Putumayo (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Mocoa', 23, 'Capital del departamento de Putumayo, ubicada en la región amazónica.', 50000),
('Colón', 23, 'Municipio agrícola en la región montañosa de Putumayo.', 6000),
('Orito', 23, 'Municipio petrolero y agrícola en Putumayo.', 20000),
('Puerto Asís', 23, 'Municipio comercial y agrícola, uno de los más grandes de Putumayo.', 70000),
('Puerto Caicedo', 23, 'Municipio agrícola y ganadero en Putumayo.', 10000),
('Puerto Guzmán', 23, 'Municipio en la región amazónica de Putumayo.', 12000),
('Puerto Leguízamo', 23, 'Municipio fronterizo con Perú, ubicado en la Amazonía.', 15000),
('San Francisco', 23, 'Municipio pequeño en la región montañosa de Putumayo.', 5000),
('San Miguel', 23, 'Municipio fronterizo con Ecuador, conocido por su producción agrícola.', 11000),
('Santiago', 23, 'Municipio en el piedemonte amazónico, con economía agrícola.', 8000),
('Sibundoy', 23, 'Municipio indígena en la región montañosa, conocido por sus tradiciones culturales.', 12000),
('Valle del Guamuez', 23, 'Municipio agrícola en el valle del Guamuez, también conocido como La Hormiga.', 15000),
('Villagarzón', 23, 'Municipio turístico y agrícola en la región amazónica.', 10000);
-- Inserción de municipios para el departamento de Quindío (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Armenia', 24, 'Capital del departamento de Quindío, conocida por su cultura cafetera.', 300000),
('Buenavista', 24, 'Municipio pequeño con economía basada en el café y el turismo.', 3000),
('Calarcá', 24, 'Municipio conocido por su producción de café y su patrimonio cultural.', 80000),
('Circasia', 24, 'Municipio turístico y caficultor, cercano a Armenia.', 27000),
('Córdoba', 24, 'Municipio productor de café, famoso por sus paisajes.', 6000),
('Filandia', 24, 'Municipio turístico, conocido como la "Colina Iluminada de los Andes".', 11000),
('Génova', 24, 'Municipio en el sur de Quindío, con economía agrícola.', 5000),
('La Tebaida', 24, 'Municipio industrial y agrícola, cercano a Armenia.', 35000),
('Montenegro', 24, 'Municipio turístico, hogar del Parque Nacional del Café.', 50000),
('Pijao', 24, 'Municipio pequeño con economía basada en el café y el turismo.', 4500),
('Quimbaya', 24, 'Municipio turístico, conocido por el Festival de Velas y Faroles.', 33000),
('Salento', 24, 'Municipio turístico, conocido por el Valle de Cocora y sus palmas de cera.', 10000);
-- Inserción de municipios para el departamento de Risaralda (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Pereira', 25, 'Capital del departamento de Risaralda, conocida por su desarrollo industrial y turístico.', 500000),
('Apía', 25, 'Municipio en la región cafetera, con una economía basada en la agricultura.', 11000),
('Balboa', 25, 'Municipio pequeño, con economía agrícola en la región cafetera.', 6000),
('Belén de Umbría', 25, 'Municipio productor de café, con un clima templado.', 20000),
('Dosquebradas', 25, 'Municipio industrial y residencial, parte del área metropolitana de Pereira.', 200000),
('Guática', 25, 'Municipio agrícola en la región cafetera de Risaralda.', 12000),
('La Celia', 25, 'Municipio pequeño, con economía basada en el café y la agricultura.', 7000),
('La Virginia', 25, 'Municipio ubicado a orillas del río Cauca, con economía agrícola e industrial.', 30000),
('Marsella', 25, 'Municipio turístico, conocido por su arquitectura y cultura cafetera.', 15000),
('Mistrató', 25, 'Municipio en la región montañosa, con población mayormente indígena.', 12000),
('Pueblo Rico', 25, 'Municipio con alta diversidad étnica y cultural.', 9000),
('Quinchía', 25, 'Municipio productor de café, conocido por sus montañas y tradiciones.', 18000),
('Santa Rosa de Cabal', 25, 'Municipio turístico, famoso por sus aguas termales.', 70000),
('Santuario', 25, 'Municipio pequeño en la región cafetera, con economía agrícola.', 10000);
-- Inserción de municipios para el departamento de San Andrés y Providencia (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('San Andrés', 26, 'Capital del departamento de San Andrés y Providencia, conocida por sus playas de arena blanca y mar de siete colores.', 65000),
('Providencia y Santa Catalina', 26, 'Municipio conformado por las islas de Providencia y Santa Catalina, conocido por su biodiversidad y ecoturismo.', 5000);
-- Inserción de municipios para el departamento de Santander (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Bucaramanga', 27, 'Capital del departamento de Santander, conocida como la "Ciudad Bonita" de Colombia.', 600000),
('Aguada', 27, 'Municipio pequeño con economía agrícola en Santander.', 3000),
('Albania', 27, 'Municipio agrícola en la región de Santander.', 5000),
('Aratoca', 27, 'Municipio turístico, conocido por su cercanía al Parque Nacional del Chicamocha.', 8000),
('Barbosa', 27, 'Municipio comercial en Santander, conocido por sus festividades culturales.', 40000),
('Barichara', 27, 'Municipio turístico, famoso por su arquitectura colonial.', 7500),
('Barrancabermeja', 27, 'Municipio industrial y petrolero en Santander.', 200000),
('Betulia', 27, 'Municipio agrícola en la región de Santander.', 10000),
('Bolívar', 27, 'Municipio pequeño en Santander, con economía agrícola.', 7000),
('Cabrera', 27, 'Municipio agrícola en la región montañosa de Santander.', 3000),
('California', 27, 'Municipio minero en Santander, conocido por sus yacimientos de oro.', 6000),
('Capitanejo', 27, 'Municipio ganadero y agrícola en Santander.', 9000),
('Carcasí', 27, 'Municipio en la región montañosa, con economía agrícola.', 3000),
('Cepitá', 27, 'Municipio turístico, cercano al Cañón del Chicamocha.', 2000),
('Cerrito', 27, 'Municipio en Santander con economía agrícola.', 5000),
('Charalá', 27, 'Municipio histórico, conocido por su papel en la independencia.', 10000),
('Charta', 27, 'Municipio pequeño en la región montañosa de Santander.', 3000),
('Chima', 27, 'Municipio agrícola en Santander.', 5000),
('Chipatá', 27, 'Municipio en la región agrícola de Santander.', 4000),
('Cimitarra', 27, 'Municipio agrícola y ganadero en Santander.', 25000),
('Concepción', 27, 'Municipio pequeño en Santander, con economía agrícola.', 3000),
('Confines', 27, 'Municipio pequeño en la región montañosa de Santander.', 2000),
('Contratación', 27, 'Municipio agrícola en Santander.', 5000),
('Coromoro', 27, 'Municipio en la región montañosa de Santander, con economía agrícola.', 4000),
('Curití', 27, 'Municipio turístico, famoso por sus cuevas y artesanías.', 10000),
('El Carmen de Chucurí', 27, 'Municipio agrícola y ganadero en Santander.', 15000),
('El Guacamayo', 27, 'Municipio pequeño en Santander, con economía agrícola.', 3000),
('El Peñón', 27, 'Municipio en la región de Santander, con economía agrícola.', 4000),
('El Playón', 27, 'Municipio agrícola y ganadero en Santander.', 10000),
('Encino', 27, 'Municipio en la región montañosa de Santander.', 3000),
('Enciso', 27, 'Municipio agrícola en Santander.', 2000),
('Florián', 27, 'Municipio en la región montañosa, conocido por sus cascadas.', 4000),
('Floridablanca', 27, 'Municipio residencial e industrial, parte del área metropolitana de Bucaramanga.', 300000),
('Galán', 27, 'Municipio pequeño en Santander, con economía agrícola.', 4000),
('Gámbita', 27, 'Municipio en la región agrícola de Santander.', 5000),
('Girón', 27, 'Municipio turístico e histórico, conocido por su arquitectura colonial.', 160000),
('Guaca', 27, 'Municipio en la región montañosa de Santander.', 6000),
('Guadalupe', 27, 'Municipio turístico, conocido por su arquitectura colonial y paisajes.', 4000),
('Guapotá', 27, 'Municipio agrícola en Santander.', 3000),
('Guavatá', 27, 'Municipio pequeño en la región agrícola de Santander.', 4000),
('Güepsa', 27, 'Municipio en la región montañosa de Santander.', 3000),
('Hato', 27, 'Municipio agrícola en la región de Santander.', 4000),
('Jesús María', 27, 'Municipio pequeño en la región agrícola de Santander.', 3000),
('Jordán', 27, 'Municipio turístico, conocido por sus paisajes montañosos.', 1000),
('La Belleza', 27, 'Municipio en la región montañosa, con economía agrícola.', 7000),
('Landázuri', 27, 'Municipio agrícola y ganadero en Santander.', 10000),
('La Paz', 27, 'Municipio en la región montañosa de Santander.', 5000),
('Lebrija', 27, 'Municipio agrícola, conocido como la "Capital Piñera de Colombia".', 40000),
('Los Santos', 27, 'Municipio turístico, famoso por el Parque Nacional del Chicamocha.', 10000),
('Macaravita', 27, 'Municipio pequeño en Santander, con economía agrícola.', 2000),
('Málaga', 27, 'Municipio agrícola y ganadero, importante centro comercial en Santander.', 15000),
('Matanza', 27, 'Municipio en la región montañosa, con economía agrícola.', 3000),
('Mogotes', 27, 'Municipio turístico y agrícola en Santander.', 9000),
('Molagavita', 27, 'Municipio pequeño en la región montañosa de Santander.', 2000),
('Ocamonte', 27, 'Municipio agrícola en Santander.', 4000),
('Oiba', 27, 'Municipio en la región agrícola de Santander.', 10000),
('Onzaga', 27, 'Municipio pequeño en la región montañosa.', 3000),
('Palmar', 27, 'Municipio agrícola en Santander.', 3000),
('Palmas del Socorro', 27, 'Municipio en la región montañosa de Santander.', 2000),
('Páramo', 27, 'Municipio pequeño en la región montañosa.', 3000),
('Piedecuesta', 27, 'Municipio residencial e industrial, parte del área metropolitana de Bucaramanga.', 150000),
('Pinchote', 27, 'Municipio en la región montañosa de Santander.', 4000),
('Puente Nacional', 27, 'Municipio agrícola en la región de Santander.', 7000),
('Puerto Parra', 27, 'Municipio agrícola en la región del Magdalena Medio.', 6000),
('Puerto Wilches', 27, 'Municipio portuario en el río Magdalena, con economía agrícola y petrolera.', 30000),
('Rionegro', 27, 'Municipio agrícola cercano a Bucaramanga.', 25000),
('Sabana de Torres', 27, 'Municipio agrícola en el Magdalena Medio.', 20000),
('San Andrés', 27, 'Municipio pequeño en Santander, con economía agrícola.', 4000),
('San Benito', 27, 'Municipio agrícola en la región de Santander.', 3000),
('San Gil', 27, 'Municipio turístico, conocido como la "Capital Turística de Santander".', 50000),
('San Joaquín', 27, 'Municipio en la región montañosa de Santander.', 3000),
('San José de Miranda', 27, 'Municipio pequeño en la región montañosa.', 2000),
('San Miguel', 27, 'Municipio en la región de Santander, con economía agrícola.', 3000),
('San Vicente de Chucurí', 27, 'Municipio agrícola, productor de cacao.', 25000),
('Santa Bárbara', 27, 'Municipio pequeño en Santander.', 2000),
('Santa Helena del Opón', 27, 'Municipio en la región montañosa.', 3000),
('Simacota', 27, 'Municipio agrícola en Santander.', 7000),
('Socorro', 27, 'Municipio histórico, conocido por su papel en la independencia.', 20000),
('Suaita', 27, 'Municipio en la región montañosa, con economía agrícola.', 5000),
('Sucre', 27, 'Municipio pequeño en Santander, con economía agrícola.', 2000),
('Suratá', 27, 'Municipio en la región montañosa de Santander.', 4000),
('Tona', 27, 'Municipio en el páramo de Santander, con economía agrícola.', 3000),
('Valle de San José', 27, 'Municipio agrícola y turístico en Santander.', 5000),
('Vélez', 27, 'Municipio conocido por su producción de bocadillo veleño.', 12000),
('Vetas', 27, 'Municipio minero en la región montañosa de Santander.', 2000),
('Villanueva', 27, 'Municipio turístico y agrícola.', 4000),
('Zapatoca', 27, 'Municipio turístico, famoso por su clima y paisajes.', 10000);
-- Inserción de municipios para el departamento de Sucre (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Sincelejo', 28, 'Capital del departamento de Sucre, conocida por su cultura ganadera y fiestas.', 280000),
('Buenavista', 28, 'Municipio agrícola, conocido por la producción de maíz y yuca.', 12000),
('Caimito', 28, 'Municipio en el valle del río San Jorge, con economía ganadera y agrícola.', 15000),
('Chalán', 28, 'Municipio pequeño con economía agrícola en Sucre.', 4000),
('Colosó', 28, 'Municipio agrícola en la región montañosa de Sucre.', 6000),
('Corozal', 28, 'Municipio comercial e industrial cercano a Sincelejo.', 57000),
('Coveñas', 28, 'Municipio turístico en la costa Caribe, conocido por sus playas.', 20000),
('El Roble', 28, 'Municipio pequeño con economía agrícola.', 7000),
('Galeras', 28, 'Municipio agrícola, productor de cultivos de maíz y yuca.', 14000),
('Guaranda', 28, 'Municipio en el sur de Sucre, con economía basada en la agricultura.', 16000),
('La Unión', 28, 'Municipio pequeño con economía agrícola en Sucre.', 6000),
('Los Palmitos', 28, 'Municipio agrícola en la región de Sucre.', 8000),
('Majagual', 28, 'Municipio en la región de la Mojana, con economía agrícola y ganadera.', 28000),
('Morroa', 28, 'Municipio agrícola conocido por su festival de gaita.', 11000),
('Ovejas', 28, 'Municipio en el norte de Sucre, famoso por sus festividades culturales.', 17000),
('Palmito', 28, 'Municipio pequeño con economía agrícola.', 5000),
('Sampués', 28, 'Municipio agrícola y ganadero, conocido por su artesanía en sombreros.', 30000),
('San Benito Abad', 28, 'Municipio en el valle del río San Jorge, con economía agrícola.', 25000),
('San Juan de Betulia', 28, 'Municipio pequeño en Sucre, con economía agrícola.', 7000),
('San Marcos', 28, 'Municipio en la región de la Mojana, con economía agrícola y ganadera.', 47000),
('San Onofre', 28, 'Municipio costero en el Caribe, con economía pesquera y agrícola.', 50000),
('San Pedro', 28, 'Municipio agrícola y ganadero en Sucre.', 15000),
('Sincé', 28, 'Municipio agrícola en Sucre, conocido por sus festividades tradicionales.', 25000),
('Sucre', 28, 'Municipio agrícola y ganadero en la región de Sucre.', 18000),
('Tolú', 28, 'Municipio turístico en la costa Caribe, conocido por sus playas.', 33000),
('Toluviejo', 28, 'Municipio pequeño con economía agrícola en Sucre.', 9000);
-- Inserción de municipios para el departamento de Tolima (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Ibagué', 29, 'Capital del departamento de Tolima, conocida como la "Capital Musical de Colombia".', 530000),
('Alpujarra', 29, 'Municipio pequeño con economía agrícola en Tolima.', 4000),
('Alvarado', 29, 'Municipio en el norte de Tolima, con producción de arroz y otros cultivos.', 10000),
('Ambalema', 29, 'Municipio histórico a orillas del río Magdalena, con economía agrícola.', 7000),
('Anzoátegui', 29, 'Municipio en la región montañosa de Tolima.', 6000),
('Armero', 29, 'Municipio conocido por la tragedia de Armero en 1985.', 12000),
('Ataco', 29, 'Municipio en el sur de Tolima, con economía agrícola.', 16000),
('Cajamarca', 29, 'Municipio agrícola, conocido como la "Despensa Agrícola de Colombia".', 20000),
('Carmen de Apicalá', 29, 'Municipio turístico en Tolima, conocido por sus termales.', 8000),
('Casabianca', 29, 'Municipio en la región cafetera de Tolima.', 5000),
('Chaparral', 29, 'Municipio en el sur de Tolima, con economía agrícola y ganadera.', 35000),
('Coello', 29, 'Municipio cercano a Ibagué, con economía basada en la agricultura.', 7000),
('Coyaima', 29, 'Municipio en el sur de Tolima, con gran población indígena.', 18000),
('Cunday', 29, 'Municipio en el norte de Tolima, conocido por sus paisajes.', 11000),
('Dolores', 29, 'Municipio pequeño con economía agrícola.', 4000),
('Espinal', 29, 'Municipio agrícola, productor de arroz y algodón.', 70000),
('Falan', 29, 'Municipio en la región montañosa de Tolima, con economía agrícola.', 5000),
('Flandes', 29, 'Municipio turístico a orillas del río Magdalena.', 25000),
('Fresno', 29, 'Municipio cafetero en el norte de Tolima.', 30000),
('Guamo', 29, 'Municipio agrícola en el sur de Tolima.', 26000),
('Herveo', 29, 'Municipio en la región cafetera de Tolima.', 5000),
('Honda', 29, 'Municipio histórico a orillas del río Magdalena, conocido por su arquitectura colonial.', 25000),
('Icononzo', 29, 'Municipio pequeño en Tolima, con economía agrícola.', 6000),
('Lérida', 29, 'Municipio agrícola en el norte de Tolima.', 20000),
('Líbano', 29, 'Municipio cafetero en el norte de Tolima.', 40000),
('Mariquita', 29, 'Municipio histórico y turístico en Tolima.', 33000),
('Melgar', 29, 'Municipio turístico, conocido por sus piscinas y clima cálido.', 40000),
('Murillo', 29, 'Municipio en la región montañosa, cercano al Nevado del Ruiz.', 4000),
('Natagaima', 29, 'Municipio en el sur de Tolima, con economía agrícola.', 17000),
('Ortega', 29, 'Municipio agrícola en el sur de Tolima.', 17000),
('Palocabildo', 29, 'Municipio en la región cafetera de Tolima.', 6000),
('Piedras', 29, 'Municipio pequeño en Tolima, con economía agrícola.', 4000),
('Planadas', 29, 'Municipio cafetero en el sur de Tolima.', 20000),
('Prado', 29, 'Municipio turístico, conocido por su represa y paisajes.', 10000),
('Purificación', 29, 'Municipio en el sur de Tolima, con economía agrícola.', 23000),
('Rio Blanco', 29, 'Municipio en el sur de Tolima, con economía agrícola y ganadera.', 13000),
('Roncesvalles', 29, 'Municipio cafetero en la región montañosa de Tolima.', 5000),
('Rovira', 29, 'Municipio agrícola cercano a Ibagué.', 18000),
('Saldaña', 29, 'Municipio en el sur de Tolima, conocido por su producción de arroz.', 12000),
('San Antonio', 29, 'Municipio agrícola en el sur de Tolima.', 6000),
('San Luis', 29, 'Municipio pequeño en Tolima, con economía agrícola.', 5000),
('Santa Isabel', 29, 'Municipio en la región montañosa, con economía cafetera.', 4000),
('Suárez', 29, 'Municipio pequeño en Tolima, con economía agrícola.', 3000),
('Valle de San Juan', 29, 'Municipio agrícola en la región de Tolima.', 7000),
('Venadillo', 29, 'Municipio agrícola en el norte de Tolima.', 13000),
('Villahermosa', 29, 'Municipio en la región cafetera de Tolima.', 11000),
('Villarrica', 29, 'Municipio en el sur de Tolima, con economía agrícola.', 6000);
-- Inserción de municipios para el departamento de Valle del Cauca (ajusta el departamento_id según el ID real en tu base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Cali', 30, 'Capital del departamento del Valle del Cauca, conocida como la "Sucursal del Cielo".', 2200000),
('Alcalá', 30, 'Municipio agrícola y turístico en el norte del Valle del Cauca.', 10000),
('Andalucía', 30, 'Municipio agrícola, conocido por su producción de caña de azúcar.', 20000),
('Ansermanuevo', 30, 'Municipio turístico y agrícola en el norte del Valle.', 15000),
('Argelia', 30, 'Municipio en el norte del Valle del Cauca, con economía agrícola.', 7000),
('Bolívar', 30, 'Municipio agrícola en el Valle, conocido por sus tradiciones culturales.', 13000),
('Buenaventura', 30, 'Principal puerto sobre el Pacífico, con economía portuaria y pesquera.', 400000),
('Buga', 30, 'Municipio turístico, conocido por la Basílica del Señor de los Milagros.', 120000),
('Bugalagrande', 30, 'Municipio agrícola, productor de caña y otros cultivos.', 20000),
('Caicedonia', 30, 'Municipio cafetero en el norte del Valle.', 28000),
('Candelaria', 30, 'Municipio agrícola cercano a Cali, conocido por sus cañaduzales.', 85000),
('Cartago', 30, 'Municipio comercial e histórico en el norte del Valle.', 130000),
('Dagua', 30, 'Municipio montañoso, conocido por su clima y atractivos turísticos.', 35000),
('El Águila', 30, 'Municipio pequeño en el norte del Valle, con economía agrícola.', 6000),
('El Cairo', 30, 'Municipio agrícola en la región montañosa del Valle.', 7000),
('El Cerrito', 30, 'Municipio agrícola y turístico, conocido por la Hacienda El Paraíso.', 55000),
('El Dovio', 30, 'Municipio pequeño con economía agrícola en el Valle del Cauca.', 8000),
('Florida', 30, 'Municipio agrícola cercano a Cali.', 60000),
('Ginebra', 30, 'Municipio turístico, famoso por su Festival de Música Andina Colombiana.', 12000),
('Guacarí', 30, 'Municipio agrícola, productor de caña y frutas.', 40000),
('Jamundí', 30, 'Municipio residencial e industrial, cercano a Cali.', 120000),
('La Cumbre', 30, 'Municipio turístico en la región montañosa del Valle.', 10000),
('La Unión', 30, 'Municipio productor de uva y vinos.', 30000),
('La Victoria', 30, 'Municipio agrícola en el norte del Valle.', 12000),
('Obando', 30, 'Municipio agrícola en el norte del Valle del Cauca.', 10000),
('Palmira', 30, 'Importante centro agrícola e industrial en el Valle, conocido como la "Villa de las Palmas".', 300000),
('Pradera', 30, 'Municipio agrícola en el Valle del Cauca.', 50000),
('Restrepo', 30, 'Municipio turístico y agrícola en el Valle.', 18000),
('Riofrío', 30, 'Municipio pequeño en el Valle, con economía agrícola.', 9000),
('Roldanillo', 30, 'Municipio turístico y cultural, famoso por el Museo Rayo.', 40000),
('San Pedro', 30, 'Municipio en el Valle del Cauca, con economía agrícola.', 20000),
('Sevilla', 30, 'Municipio cafetero en el norte del Valle.', 45000),
('Toro', 30, 'Municipio agrícola en el Valle del Cauca.', 8000),
('Trujillo', 30, 'Municipio agrícola, productor de café y caña.', 18000),
('Tuluá', 30, 'Municipio comercial y agrícola, conocido como el "Corazón del Valle".', 220000),
('Ulloa', 30, 'Municipio pequeño en el norte del Valle del Cauca.', 5000),
('Versalles', 30, 'Municipio agrícola en la región montañosa del Valle.', 8000),
('Vijes', 30, 'Municipio en el Valle, con economía basada en la agricultura.', 6000),
('Yotoco', 30, 'Municipio pequeño en el Valle, productor de caña de azúcar.', 12000),
('Yumbo', 30, 'Municipio industrial en el Valle, conocido por su zona franca.', 120000),
('Zarzal', 30, 'Municipio agrícola y comercial en el Valle del Cauca.', 40000);
-- Inserción de municipios para el departamento de Vaupés (ajusta el departamento_id según el ID real en la base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Mitú', 31, 'Capital del departamento de Vaupés, ubicada en la Amazonía colombiana.', 15000),
('Carurú', 31, 'Municipio en la Amazonía, con una población mayormente indígena.', 5000),
('Pacoa', 31, 'Corregimiento en la región amazónica, con economía basada en la pesca y agricultura.', 2000),
('Papunaua', 31, 'Corregimiento en la región amazónica, con una pequeña población indígena.', 1000),
('Taraira', 31, 'Municipio en el sur de Vaupés, fronterizo con Brasil, con una economía rural.', 3000),
('Yavaraté', 31, 'Corregimiento indígena en la región amazónica de Vaupés.', 1200);
-- Inserción de municipios para el departamento de Vichada (ajusta el departamento_id según el ID real en la base de datos)
INSERT INTO municipios (nombre, departamento_id, descripcion, habitantes) VALUES
('Puerto Carreño', 32, 'Capital del departamento de Vichada, ubicada en la frontera con Venezuela.', 15000),
('Cumaribo', 32, 'Municipio más extenso de Colombia, con economía basada en la ganadería y agricultura.', 20000),
('La Primavera', 32, 'Municipio agrícola en Vichada, con una economía rural.', 5000),
('Santa Rosalía', 32, 'Municipio pequeño en Vichada, con economía agrícola y ganadera.', 4000);
